name: countdowns
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0+4

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  path_provider: ^2.0.8
  auto_size_text: ^3.0.0
  package_info_plus: ^4.1.0
  url_launcher: ^6.0.17
  store_redirect: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: ComicNeue
      fonts:
        - asset: fonts/ComicNeue-Regular.ttf
          weight: 400
        - asset: fonts/ComicNeue-Light.ttf
          weight: 300
        - asset: fonts/ComicNeue-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
    - family: LibreBaskerville
      fonts:
        - asset: fonts/LibreBaskerville-Regular.ttf
          weight: 400
        - asset: fonts/LibreBaskerville-Italic.ttf
          weight: 300
        - asset: fonts/LibreBaskerville-Bold.ttf
          weight: 700
    - family: CarnivaleeFreakshow
      fonts:
        - asset: fonts/CarnivaleeFreakshow-Regular.ttf
          weight: 400
    - family: GoodTimes
      fonts:
        - asset: fonts/GoodTimes-Regular.otf
          weight: 400
    - family: LuxuriousRoman
      fonts:
        - asset: fonts/LuxuriousRoman-Regular.ttf
          weight: 400
    - family: Starjedi
      fonts:
        - asset: fonts/Starjedi.ttf
          weight: 400
    - family: Sunnyspells
      fonts:
        - asset: fonts/Sunnyspells.otf
          weight: 400
    - family: NewWaltDisney
      fonts:
        - asset: fonts/NewWaltDisney.ttf
          weight: 400
    - family: DiarioDeAndy
      fonts:
        - asset: fonts/DiarioDeAndy.otf
          weight: 400
